# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auth_pb2 as auth__pb2
import room_pb2 as room__pb2
import presence_pb2 as presence__pb2
import message_pb2 as message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\ngateway.v1\x1a\nauth.proto\x1a\nroom.proto\x1a\x0epresence.proto\x1a\rmessage.proto\"6\n\tReplayReq\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x18\n\x10last_seen_offset\x18\x02 \x01(\x03\x32\x94\x08\n\x0eGatewayService\x12;\n\x08Register\x12\x18.auth.v1.RegisterRequest\x1a\x15.auth.v1.AuthResponse\x12\x35\n\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x15.auth.v1.AuthResponse\x12&\n\x06Logout\x12\x0e.auth.v1.Token\x1a\x0c.auth.v1.Ack\x12)\n\x07GetUser\x12\x0f.auth.v1.UserId\x1a\r.auth.v1.User\x12\x32\n\nCreateRoom\x12\x16.room.v1.CreateRoomReq\x1a\x0c.room.v1.Ack\x12/\n\x08JoinRoom\x12\x15.room.v1.JoinLeaveReq\x1a\x0c.room.v1.Ack\x12\x30\n\tLeaveRoom\x12\x15.room.v1.JoinLeaveReq\x1a\x0c.room.v1.Ack\x12,\n\tListRooms\x12\x0e.room.v1.Empty\x1a\r.room.v1.Room0\x01\x12\x31\n\x0bListMembers\x12\x0f.room.v1.RoomId\x1a\x0f.room.v1.Member0\x01\x12\x38\n\tHeartbeat\x12\x19.presence.v1.HeartbeatReq\x1a\x10.presence.v1.Ack\x12\x46\n\x11SubscribePresence\x12\x13.presence.v1.RoomId\x1a\x1a.presence.v1.PresenceEvent0\x01\x12\x37\n\x06Roster\x12\x13.presence.v1.RoomId\x1a\x18.presence.v1.RosterReply\x12\x37\n\x06\x41ppend\x12\x15.message.v1.AppendReq\x1a\x16.message.v1.AppendResp\x12.\n\x04List\x12\x13.message.v1.ListReq\x1a\x0f.message.v1.Msg0\x01\x12>\n\x12ReplayAndSubscribe\x12\x15.gateway.v1.ReplayReq\x1a\x0f.message.v1.Msg0\x01\x12L\n\rPrepareAppend\x12\x1c.message.v1.PrepareAppendReq\x1a\x1d.message.v1.PrepareAppendResp\x12I\n\x0c\x43ommitAppend\x12\x1b.message.v1.CommitAppendReq\x1a\x1c.message.v1.CommitAppendResp\x12\x46\n\x0b\x41\x62ortAppend\x12\x1a.message.v1.AbortAppendReq\x1a\x1b.message.v1.AbortAppendRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLAYREQ']._serialized_start=84
  _globals['_REPLAYREQ']._serialized_end=138
  _globals['_GATEWAYSERVICE']._serialized_start=141
  _globals['_GATEWAYSERVICE']._serialized_end=1185
# @@protoc_insertion_point(module_scope)
