# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_pb2 as auth__pb2
import gateway_pb2 as gateway__pb2
import message_pb2 as message__pb2
import presence_pb2 as presence__pb2
import room_pb2 as room__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/gateway.v1.GatewayService/Register',
                request_serializer=auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/gateway.v1.GatewayService/Login',
                request_serializer=auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/gateway.v1.GatewayService/Logout',
                request_serializer=auth__pb2.Token.SerializeToString,
                response_deserializer=auth__pb2.Ack.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/gateway.v1.GatewayService/GetUser',
                request_serializer=auth__pb2.UserId.SerializeToString,
                response_deserializer=auth__pb2.User.FromString,
                _registered_method=True)
        self.CreateRoom = channel.unary_unary(
                '/gateway.v1.GatewayService/CreateRoom',
                request_serializer=room__pb2.CreateRoomReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.JoinRoom = channel.unary_unary(
                '/gateway.v1.GatewayService/JoinRoom',
                request_serializer=room__pb2.JoinLeaveReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.LeaveRoom = channel.unary_unary(
                '/gateway.v1.GatewayService/LeaveRoom',
                request_serializer=room__pb2.JoinLeaveReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_stream(
                '/gateway.v1.GatewayService/ListRooms',
                request_serializer=room__pb2.Empty.SerializeToString,
                response_deserializer=room__pb2.Room.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_stream(
                '/gateway.v1.GatewayService/ListMembers',
                request_serializer=room__pb2.RoomId.SerializeToString,
                response_deserializer=room__pb2.Member.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gateway.v1.GatewayService/Heartbeat',
                request_serializer=presence__pb2.HeartbeatReq.SerializeToString,
                response_deserializer=presence__pb2.Ack.FromString,
                _registered_method=True)
        self.SubscribePresence = channel.unary_stream(
                '/gateway.v1.GatewayService/SubscribePresence',
                request_serializer=presence__pb2.RoomId.SerializeToString,
                response_deserializer=presence__pb2.PresenceEvent.FromString,
                _registered_method=True)
        self.Roster = channel.unary_unary(
                '/gateway.v1.GatewayService/Roster',
                request_serializer=presence__pb2.RoomId.SerializeToString,
                response_deserializer=presence__pb2.RosterReply.FromString,
                _registered_method=True)
        self.Append = channel.unary_unary(
                '/gateway.v1.GatewayService/Append',
                request_serializer=message__pb2.AppendReq.SerializeToString,
                response_deserializer=message__pb2.AppendResp.FromString,
                _registered_method=True)
        self.List = channel.unary_stream(
                '/gateway.v1.GatewayService/List',
                request_serializer=message__pb2.ListReq.SerializeToString,
                response_deserializer=message__pb2.Msg.FromString,
                _registered_method=True)
        self.ReplayAndSubscribe = channel.unary_stream(
                '/gateway.v1.GatewayService/ReplayAndSubscribe',
                request_serializer=gateway__pb2.ReplayReq.SerializeToString,
                response_deserializer=message__pb2.Msg.FromString,
                _registered_method=True)
        self.PrepareAppend = channel.unary_unary(
                '/gateway.v1.GatewayService/PrepareAppend',
                request_serializer=message__pb2.PrepareAppendReq.SerializeToString,
                response_deserializer=message__pb2.PrepareAppendResp.FromString,
                _registered_method=True)
        self.CommitAppend = channel.unary_unary(
                '/gateway.v1.GatewayService/CommitAppend',
                request_serializer=message__pb2.CommitAppendReq.SerializeToString,
                response_deserializer=message__pb2.CommitAppendResp.FromString,
                _registered_method=True)
        self.AbortAppend = channel.unary_unary(
                '/gateway.v1.GatewayService/AbortAppend',
                request_serializer=message__pb2.AbortAppendReq.SerializeToString,
                response_deserializer=message__pb2.AbortAppendResp.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Auth proxies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Room
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Presence
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Roster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """Messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayAndSubscribe(self, request, context):
        """Resume helper
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareAppend(self, request, context):
        """-------------------------------------
        2PC SUPPORT — FIXED WITH CORRECT NAMES
        -------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auth__pb2.RegisterRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=auth__pb2.Token.FromString,
                    response_serializer=auth__pb2.Ack.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__pb2.UserId.FromString,
                    response_serializer=auth__pb2.User.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=room__pb2.CreateRoomReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=room__pb2.JoinLeaveReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'LeaveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveRoom,
                    request_deserializer=room__pb2.JoinLeaveReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'ListRooms': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=room__pb2.Empty.FromString,
                    response_serializer=room__pb2.Room.SerializeToString,
            ),
            'ListMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=room__pb2.RoomId.FromString,
                    response_serializer=room__pb2.Member.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=presence__pb2.HeartbeatReq.FromString,
                    response_serializer=presence__pb2.Ack.SerializeToString,
            ),
            'SubscribePresence': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePresence,
                    request_deserializer=presence__pb2.RoomId.FromString,
                    response_serializer=presence__pb2.PresenceEvent.SerializeToString,
            ),
            'Roster': grpc.unary_unary_rpc_method_handler(
                    servicer.Roster,
                    request_deserializer=presence__pb2.RoomId.FromString,
                    response_serializer=presence__pb2.RosterReply.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=message__pb2.AppendReq.FromString,
                    response_serializer=message__pb2.AppendResp.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=message__pb2.ListReq.FromString,
                    response_serializer=message__pb2.Msg.SerializeToString,
            ),
            'ReplayAndSubscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.ReplayAndSubscribe,
                    request_deserializer=gateway__pb2.ReplayReq.FromString,
                    response_serializer=message__pb2.Msg.SerializeToString,
            ),
            'PrepareAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareAppend,
                    request_deserializer=message__pb2.PrepareAppendReq.FromString,
                    response_serializer=message__pb2.PrepareAppendResp.SerializeToString,
            ),
            'CommitAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitAppend,
                    request_deserializer=message__pb2.CommitAppendReq.FromString,
                    response_serializer=message__pb2.CommitAppendResp.SerializeToString,
            ),
            'AbortAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortAppend,
                    request_deserializer=message__pb2.AbortAppendReq.FromString,
                    response_serializer=message__pb2.AbortAppendResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Register',
            auth__pb2.RegisterRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Login',
            auth__pb2.LoginRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Logout',
            auth__pb2.Token.SerializeToString,
            auth__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/GetUser',
            auth__pb2.UserId.SerializeToString,
            auth__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/CreateRoom',
            room__pb2.CreateRoomReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/JoinRoom',
            room__pb2.JoinLeaveReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/LeaveRoom',
            room__pb2.JoinLeaveReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.GatewayService/ListRooms',
            room__pb2.Empty.SerializeToString,
            room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.GatewayService/ListMembers',
            room__pb2.RoomId.SerializeToString,
            room__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Heartbeat',
            presence__pb2.HeartbeatReq.SerializeToString,
            presence__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.GatewayService/SubscribePresence',
            presence__pb2.RoomId.SerializeToString,
            presence__pb2.PresenceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Roster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Roster',
            presence__pb2.RoomId.SerializeToString,
            presence__pb2.RosterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/Append',
            message__pb2.AppendReq.SerializeToString,
            message__pb2.AppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.GatewayService/List',
            message__pb2.ListReq.SerializeToString,
            message__pb2.Msg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayAndSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.GatewayService/ReplayAndSubscribe',
            gateway__pb2.ReplayReq.SerializeToString,
            message__pb2.Msg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/PrepareAppend',
            message__pb2.PrepareAppendReq.SerializeToString,
            message__pb2.PrepareAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/CommitAppend',
            message__pb2.CommitAppendReq.SerializeToString,
            message__pb2.CommitAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/AbortAppend',
            message__pb2.AbortAppendReq.SerializeToString,
            message__pb2.AbortAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
