# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/message.v1.MessageService/Append',
                request_serializer=message__pb2.AppendReq.SerializeToString,
                response_deserializer=message__pb2.AppendResp.FromString,
                _registered_method=True)
        self.List = channel.unary_stream(
                '/message.v1.MessageService/List',
                request_serializer=message__pb2.ListReq.SerializeToString,
                response_deserializer=message__pb2.Msg.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/message.v1.MessageService/Subscribe',
                request_serializer=message__pb2.RoomId.SerializeToString,
                response_deserializer=message__pb2.Msg.FromString,
                _registered_method=True)
        self.NextOffset = channel.unary_unary(
                '/message.v1.MessageService/NextOffset',
                request_serializer=message__pb2.RoomId.SerializeToString,
                response_deserializer=message__pb2.Offset.FromString,
                _registered_method=True)
        self.PrepareAppend = channel.unary_unary(
                '/message.v1.MessageService/PrepareAppend',
                request_serializer=message__pb2.PrepareAppendReq.SerializeToString,
                response_deserializer=message__pb2.PrepareAppendResp.FromString,
                _registered_method=True)
        self.CommitAppend = channel.unary_unary(
                '/message.v1.MessageService/CommitAppend',
                request_serializer=message__pb2.CommitAppendReq.SerializeToString,
                response_deserializer=message__pb2.CommitAppendResp.FromString,
                _registered_method=True)
        self.AbortAppend = channel.unary_unary(
                '/message.v1.MessageService/AbortAppend',
                request_serializer=message__pb2.AbortAppendReq.SerializeToString,
                response_deserializer=message__pb2.AbortAppendResp.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Append(self, request, context):
        """Original functionality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareAppend(self, request, context):
        """2PC Phase 1 + Phase 2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=message__pb2.AppendReq.FromString,
                    response_serializer=message__pb2.AppendResp.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=message__pb2.ListReq.FromString,
                    response_serializer=message__pb2.Msg.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=message__pb2.RoomId.FromString,
                    response_serializer=message__pb2.Msg.SerializeToString,
            ),
            'NextOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.NextOffset,
                    request_deserializer=message__pb2.RoomId.FromString,
                    response_serializer=message__pb2.Offset.SerializeToString,
            ),
            'PrepareAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareAppend,
                    request_deserializer=message__pb2.PrepareAppendReq.FromString,
                    response_serializer=message__pb2.PrepareAppendResp.SerializeToString,
            ),
            'CommitAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitAppend,
                    request_deserializer=message__pb2.CommitAppendReq.FromString,
                    response_serializer=message__pb2.CommitAppendResp.SerializeToString,
            ),
            'AbortAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortAppend,
                    request_deserializer=message__pb2.AbortAppendReq.FromString,
                    response_serializer=message__pb2.AbortAppendResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.v1.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.v1.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.v1.MessageService/Append',
            message__pb2.AppendReq.SerializeToString,
            message__pb2.AppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/message.v1.MessageService/List',
            message__pb2.ListReq.SerializeToString,
            message__pb2.Msg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/message.v1.MessageService/Subscribe',
            message__pb2.RoomId.SerializeToString,
            message__pb2.Msg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NextOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.v1.MessageService/NextOffset',
            message__pb2.RoomId.SerializeToString,
            message__pb2.Offset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.v1.MessageService/PrepareAppend',
            message__pb2.PrepareAppendReq.SerializeToString,
            message__pb2.PrepareAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.v1.MessageService/CommitAppend',
            message__pb2.CommitAppendReq.SerializeToString,
            message__pb2.CommitAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.v1.MessageService/AbortAppend',
            message__pb2.AbortAppendReq.SerializeToString,
            message__pb2.AbortAppendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
