# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: presence.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epresence.proto\x12\x0bpresence.v1\"\x19\n\x06RoomId\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"F\n\x0cHeartbeatReq\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\" \n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"K\n\x0cPresenceUser\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x14\n\x0clast_seen_ms\x18\x03 \x01(\x03\"7\n\x0bRosterReply\x12(\n\x05users\x18\x01 \x03(\x0b\x32\x19.presence.v1.PresenceUser\"\x7f\n\rPresenceEvent\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.presence.v1.PresenceType\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\r\n\x05ts_ms\x18\x05 \x01(\x03*#\n\x0cPresenceType\x12\x08\n\x04JOIN\x10\x00\x12\t\n\x05LEAVE\x10\x01\x32\xcc\x01\n\x0fPresenceService\x12\x38\n\tHeartbeat\x12\x19.presence.v1.HeartbeatReq\x1a\x10.presence.v1.Ack\x12\x37\n\x06Roster\x12\x13.presence.v1.RoomId\x1a\x18.presence.v1.RosterReply\x12\x46\n\x11SubscribePresence\x12\x13.presence.v1.RoomId\x1a\x1a.presence.v1.PresenceEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESENCETYPE']._serialized_start=427
  _globals['_PRESENCETYPE']._serialized_end=462
  _globals['_ROOMID']._serialized_start=31
  _globals['_ROOMID']._serialized_end=56
  _globals['_HEARTBEATREQ']._serialized_start=58
  _globals['_HEARTBEATREQ']._serialized_end=128
  _globals['_ACK']._serialized_start=130
  _globals['_ACK']._serialized_end=162
  _globals['_PRESENCEUSER']._serialized_start=164
  _globals['_PRESENCEUSER']._serialized_end=239
  _globals['_ROSTERREPLY']._serialized_start=241
  _globals['_ROSTERREPLY']._serialized_end=296
  _globals['_PRESENCEEVENT']._serialized_start=298
  _globals['_PRESENCEEVENT']._serialized_end=425
  _globals['_PRESENCESERVICE']._serialized_start=465
  _globals['_PRESENCESERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
