# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import room_pb2 as room__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
                '/room.v1.RoomService/CreateRoom',
                request_serializer=room__pb2.CreateRoomReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.JoinRoom = channel.unary_unary(
                '/room.v1.RoomService/JoinRoom',
                request_serializer=room__pb2.JoinLeaveReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.LeaveRoom = channel.unary_unary(
                '/room.v1.RoomService/LeaveRoom',
                request_serializer=room__pb2.JoinLeaveReq.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_stream(
                '/room.v1.RoomService/ListRooms',
                request_serializer=room__pb2.Empty.SerializeToString,
                response_deserializer=room__pb2.Room.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_stream(
                '/room.v1.RoomService/ListMembers',
                request_serializer=room__pb2.RoomId.SerializeToString,
                response_deserializer=room__pb2.Member.FromString,
                _registered_method=True)
        self.RoomExists = channel.unary_unary(
                '/room.v1.RoomService/RoomExists',
                request_serializer=room__pb2.RoomId.SerializeToString,
                response_deserializer=room__pb2.Ack.FromString,
                _registered_method=True)


class RoomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoomExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=room__pb2.CreateRoomReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=room__pb2.JoinLeaveReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'LeaveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveRoom,
                    request_deserializer=room__pb2.JoinLeaveReq.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
            'ListRooms': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=room__pb2.Empty.FromString,
                    response_serializer=room__pb2.Room.SerializeToString,
            ),
            'ListMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=room__pb2.RoomId.FromString,
                    response_serializer=room__pb2.Member.SerializeToString,
            ),
            'RoomExists': grpc.unary_unary_rpc_method_handler(
                    servicer.RoomExists,
                    request_deserializer=room__pb2.RoomId.FromString,
                    response_serializer=room__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'room.v1.RoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('room.v1.RoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.v1.RoomService/CreateRoom',
            room__pb2.CreateRoomReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.v1.RoomService/JoinRoom',
            room__pb2.JoinLeaveReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.v1.RoomService/LeaveRoom',
            room__pb2.JoinLeaveReq.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/room.v1.RoomService/ListRooms',
            room__pb2.Empty.SerializeToString,
            room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/room.v1.RoomService/ListMembers',
            room__pb2.RoomId.SerializeToString,
            room__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RoomExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.v1.RoomService/RoomExists',
            room__pb2.RoomId.SerializeToString,
            room__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
