# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x12\x07room.v1\"\x07\n\x05\x45mpty\"%\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\".\n\rCreateRoomReq\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\x06RoomId\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"%\n\x04Room\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"*\n\x06Member\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\"0\n\x0cJoinLeaveReq\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xb2\x02\n\x0bRoomService\x12\x32\n\nCreateRoom\x12\x16.room.v1.CreateRoomReq\x1a\x0c.room.v1.Ack\x12/\n\x08JoinRoom\x12\x15.room.v1.JoinLeaveReq\x1a\x0c.room.v1.Ack\x12\x30\n\tLeaveRoom\x12\x15.room.v1.JoinLeaveReq\x1a\x0c.room.v1.Ack\x12,\n\tListRooms\x12\x0e.room.v1.Empty\x1a\r.room.v1.Room0\x01\x12\x31\n\x0bListMembers\x12\x0f.room.v1.RoomId\x1a\x0f.room.v1.Member0\x01\x12+\n\nRoomExists\x12\x0f.room.v1.RoomId\x1a\x0c.room.v1.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_ACK']._serialized_start=32
  _globals['_ACK']._serialized_end=69
  _globals['_CREATEROOMREQ']._serialized_start=71
  _globals['_CREATEROOMREQ']._serialized_end=117
  _globals['_ROOMID']._serialized_start=119
  _globals['_ROOMID']._serialized_end=144
  _globals['_ROOM']._serialized_start=146
  _globals['_ROOM']._serialized_end=183
  _globals['_MEMBER']._serialized_start=185
  _globals['_MEMBER']._serialized_end=227
  _globals['_JOINLEAVEREQ']._serialized_start=229
  _globals['_JOINLEAVEREQ']._serialized_end=277
  _globals['_ROOMSERVICE']._serialized_start=280
  _globals['_ROOMSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
