# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\":\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"\x9e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"K\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x05\"\"\n\rClientCommand\x12\x11\n\toperation\x18\x01 \x01(\t\"B\n\x0b\x43lientReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xc6\x01\n\x0bRaftService\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12\x37\n\rClientRequest\x12\x13.raft.ClientCommand\x1a\x11.raft.ClientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=116
  _globals['_VOTERESPONSE']._serialized_start=118
  _globals['_VOTERESPONSE']._serialized_end=168
  _globals['_LOGENTRY']._serialized_start=170
  _globals['_LOGENTRY']._serialized_end=228
  _globals['_APPENDENTRIESREQUEST']._serialized_start=231
  _globals['_APPENDENTRIESREQUEST']._serialized_end=389
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=391
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=466
  _globals['_CLIENTCOMMAND']._serialized_start=468
  _globals['_CLIENTCOMMAND']._serialized_end=502
  _globals['_CLIENTREPLY']._serialized_start=504
  _globals['_CLIENTREPLY']._serialized_end=570
  _globals['_RAFTSERVICE']._serialized_start=573
  _globals['_RAFTSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
